
---
- hosts: server1
  become: yes
  tasks:
  - name: play 1
    apt:
      name: tree
      state: present

  - name : create file
    command: touch /home/swapnil/a3

-
  name: play 2
  hosts: server1
  tasks: 
  - 
    name: create directory 1
    command: mkdir /home/swapnil/dir1

  -
    name: create directory 3
    command: mkdir /home/swapnil/dir3    

-
  name: play 3
  hosts: server1
  tasks:
  - 
    name: install wget
    apt:
     name: wget
     state: present

  -
    name: create dirctory 2
    command: mkdir /home/swapnil/dir2  

    