---
- name: module 1
  hosts: server1
  become: yes
  var_files:
   - variable.yml 
  tasks:  
  - 
    name: task1
    command: touch /home/swapnil/{{ var1 }}

  - 
    name: task2
    command: touch /home/swapnil/{{ var2 }}  

  - 
    name: task3
    command: touch /home/swapnil/{{ var3 }}

 